### ISSUE TITLE
No supported some characters

### ISSUE THREAD

**Issue by gdlm91** [djpate/docxgen#1]
Hi there, was doing some tests and found that lil bug, has no support for some characters like ñ/Ñ... Could u take a look at that..?.. when i trie to open the .docs just says "The file XYZ.docx cannot be opened because there are problems with the contents"...

Really need that lil thing working... 

Good Luck sir...

**Comment by djpate** [comment]
I just tried with that https://gist.github.com/992578 but had no issue, maybe it's another character ? I know & made a problem maybe it's something trivial like ; or something

**Comment by gdlm91** [comment]
Apparently just happen when i write direct in the code. Put some Ñ on my database and works just fine... Maybe the problem are my headers... Thanks for the review...
